/* WAP that accept basic salary of an employee and display gross salary, net salary generated by below formula.
    DA = 25% of the basic salary.
    HRA = 12.5% of the basic salary.
    PF = 10% of the basic salary.
    gross salary = basic salary + da + hra
    net salary = gross salary - pf */