/*
 * ======================================================================================
 * COPYRIGHT (C) 2025 AMIT DUTTA. ALL RIGHTS RESERVED.
 * Repository : https://github.com/notamitgamer/bsc
 * License    : ESAL-1.0 ( https://esal.amit.is-a.dev/ )
 * ======================================================================================
 * [ ACADEMIC INTEGRITY WARNING ]
 * The use of this code for academic assignments at ANY educational institution,
 * college, or university is STRICTLY PROHIBITED.
 * Any other use requires prior written permission from the author.
 * Violations will be reported as academic misconduct.
 * ======================================================================================
 */

/* WAP that accept basic salary of an employee and display gross salary,
net salary generated by below formula.
    DA = 25% of the basic salary.
    HRA = 12.5% of the basic salary.
    PF = 10% of the basic salary.
    gross salary = basic salary + da + hra
    net salary = gross salary - pf
*/
/* Author - Amit Dutta, Date - 19th SEP, 2025 */

#include <stdio.h>
int main()
{
    double bs, gs, ns, da, hra, pf;
    printf("Enter the basic salary of the employee : ");
    scanf("%lf", &bs);
    da = bs * 0.25;
    hra = bs * 0.125;
    pf = bs * 0.10;
    gs = bs + da + hra;
    ns = gs - pf;
    printf("\nGross Salary : %g"
           "\nNet Salary   : %g",
           gs, ns);
    return 0;
}