/*
 * Author: Amit Dutta (amitdutta4255@gmail.com) | Date: 12 Dec 2025
 * Repo: https://github.com/notamitgamer/bsc
 * License: MIT | Copyright (c) 2025 Amit Dutta
 */

/* WAP that accept basic salary of an employee and display gross salary,
net salary generated by below formula.
    DA = 25% of the basic salary.
    HRA = 12.5% of the basic salary.
    PF = 10% of the basic salary.
    gross salary = basic salary + da + hra
    net salary = gross salary - pf
*/
/* Author - Amit Dutta, Date - 19th SEP, 2025 */

#include <stdio.h>
int main()
{
    double bs, gs, ns, da, hra, pf;
    printf("Enter the basic salary of the employee : ");
    scanf("%lf", &bs);
    da = bs * 0.25;
    hra = bs * 0.125;
    pf = bs * 0.10;
    gs = bs + da + hra;
    ns = gs - pf;
    printf("\nGross Salary : %g"
           "\nNet Salary   : %g",
           gs, ns);
    return 0;
}