site_name: BSc Code Index · v3.2.6
site_description: C programming assignments, indexed and documented.

repo_url: https://github.com/notamitgamer/bsc
repo_name: notamitgamer/bsc
edit_uri: edit/main/docs-temp/

theme:
  name: material
  custom_dir: docs-temp\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Readex Pro
    code: Fira Code

  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - search.share
    - content.tooltips
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.instant
    - announce.dismiss

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

copyright: >
  Copyright &copy; 2025–2026
  <a href="https://amit.is-a.dev" target="_blank">amit.is-a.dev</a> /
  <a href="https://github.com/notamitgamer" target="_blank">notamitgamer</a>
  <br>
  <a href="https://github.com/notamitgamer/bsc/blob/main/LICENSE" target="_blank">MIT License</a>

docs_dir: docs-temp

extra:
  generator: false
  announce: "Welcome to the new code.amit.is-a.dev! The BSc Code Index has been completely rebuilt from the ground up for a cleaner UI, faster navigation, and a rock-solid, bug-free experience."