/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to copy contents of one file to another. While doing so replace all lowercase characters to their equivalent uppercase characters.
*/
/* Let Us C, Chap- 19 (File Input/Output), Qn No.: B(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

void create_source_file();

int main()
{
    FILE *fs, *ft;
    char ch;

    create_source_file(); // Helper to make code runnable

    fs = fopen("source.txt", "r");
    if (fs == NULL)
    {
        printf("Cannot open source file.\n");
        exit(1);
    }

    ft = fopen("target.txt", "w");
    if (ft == NULL)
    {
        printf("Cannot open target file.\n");
        fclose(fs);
        exit(2);
    }

    while ((ch = fgetc(fs)) != EOF)
    {
        ch = toupper(ch);
        fputc(ch, ft);
    }

    printf("File copied successfully with uppercase conversion.\n");
    printf("Check 'target.txt' for results.\n");

    fclose(fs);
    fclose(ft);

    return 0;
}

void create_source_file()
{
    FILE *fp = fopen("source.txt", "w");
    if (fp)
    {
        fprintf(fp, "This is a sample text.\nIt contains Lowercase letters.\n");
        fclose(fp);
    }
}