/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* For the following set of sample data, compute the standard deviation and the mean.\nData: -6, -12, 8, 13, 11, 6, 7, 2, -6, -9, -10, 11, 10, 9, 2
*/

/* Let Us C, Chap- 13 (Arrays), Qn No.: B(f) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main()
{
    int data[] = {-6, -12, 8, 13, 11, 6, 7, 2, -6, -9, -10, 11, 10, 9, 2};
    int n = 15, i;
    double sum = 0.0, mean, std_dev = 0.0;

    // Calculate Mean
    for (i = 0; i < n; i++)
    {
        sum += data[i];
    }
    mean = sum / n;

    // Calculate Standard Deviation
    for (i = 0; i < n; i++)
    {
        std_dev += pow(data[i] - mean, 2);
    }
    std_dev = sqrt(std_dev / n);

    printf("Count: %d\n", n);
    printf("Mean: %.2f\n", mean);
    printf("Standard Deviation: %.2f\n", std_dev);

    return 0;
}