/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* A positive integer is entered through the keyboard, write a function to find the binary equivalent of this number:
(1) Without using recursion
(2) Using recursion
*/
/* Let Us C, Chap- 10 (Recursive), Qn No.: B(a) */
/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int binary_non_rec(int);
void binary_rec(int);

int main()
{
    int num, bin;

    printf("Enter a positive integer: ");
    scanf("%d", &num);

    bin = binary_non_rec(num);
    printf("Binary (Non-Recursive): %d\n", bin);

    printf("Binary (Recursive): ");
    binary_rec(num);
    printf("\n");

    return 0;
}

int binary_non_rec(int n)
{
    int rem, i = 1, bin = 0;
    while (n != 0)
    {
        rem = n % 2;
        n = n / 2;
        bin = bin + rem * i;
        i = i * 10;
    }
    return bin;
}

void binary_rec(int n)
{
    if (n > 1)
        binary_rec(n / 2);
    
    printf("%d", n % 2);
}