/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program that can copy the contents of one file to another. The source and target filenames should be supplied as command-line arguments.
*/
/* Let Us C, Chap- 20 (More Issues In Input/Output), Qn No.: A(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

int main(int argc, char *argv[])
{
    FILE *fs, *ft;
    char ch;

    /* Check for correct number of arguments */
    if (argc != 3)
    {
        printf("Usage: %s <source_file> <target_file>\n", argv[0]);
        exit(1);
    }

    fs = fopen(argv[1], "r");
    if (fs == NULL)
    {
        printf("Error: Cannot open source file '%s'\n", argv[1]);
        exit(2);
    }

    ft = fopen(argv[2], "w");
    if (ft == NULL)
    {
        printf("Error: Cannot create target file '%s'\n", argv[2]);
        fclose(fs);
        exit(3);
    }

    /* Copy contents */
    while ((ch = fgetc(fs)) != EOF)
    {
        fputc(ch, ft);
    }

    printf("File copied successfully.\n");

    fclose(fs);
    fclose(ft);
    return 0;
}