/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to delete all vowels from a sentence. Assume that the sentence is not more than 80 characters long.
*/

/* Let Us C, Chap- 16 (Handling Multiple Strings), Qn No.: A(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

int main()
{
    char str[81], res[81];
    int i, j = 0;

    printf("Enter a sentence (max 80 chars): ");
    gets(str); // Note: gets is deprecated, but used here for simplicity as per classic C texts

    for (i = 0; str[i] != '\0'; i++)
    {
        char ch = tolower(str[i]);
        if (ch == 'a' || ch == 'e' || ch == 'i' || ch == 'o' || ch == 'u')
        {
            // Skip vowel
            continue;
        }
        else
        {
            res[j] = str[i];
            j++;
        }
    }
    res[j] = '\0';

    printf("Sentence without vowels: %s\n", res);

    return 0;
}