/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Read an integer 'game' representing sports won by a college. Determine if it won the 'Champion of Champions' trophy (>5 games) and list games won.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: A(a) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    int game;
    int count = 0, i;
    const char *sports[] = {
        "Cricket", "Basketball", "Football", "Hockey", 
        "Lawn Tennis", "Table Tennis", "Carom", "Chess", "Volleyball" // Added one for bit 8
    };

    printf("Enter the game information (integer): ");
    scanf("%d", &game);

    printf("\nGames won:\n");
    for (i = 0; i <= 8; i++)
    {
        if (game & (1 << i))
        {
            printf("- %s\n", sports[i]);
            count++;
        }
    }

    printf("\nTotal games won: %d\n", count);

    if (count >= 5)
        printf("Result: The college won the Champion of Champions trophy.\n");
    else
        printf("Result: The college did NOT win the trophy.\n");

    return 0;
}