/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Tower of Hanoi: Write a program to print out the sequence in which 4 disks should be moved from peg A to peg C using peg B.
*/
/* Let Us C, Chap- 10 (Recursive), Qn No.: B(c) */
/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

void hanoi(int, char, char, char);

int main()
{
    int n = 4; 

    printf("Sequence of moves for %d disks:\n\n", n);
    hanoi(n, 'A', 'B', 'C');

    return 0;
}

void hanoi(int n, char from_rod, char aux_rod, char to_rod)
{
    if (n == 1)
    {
        printf("Move disk 1 from rod %c to rod %c\n", from_rod, to_rod);
        return;
    }
    hanoi(n - 1, from_rod, to_rod, aux_rod);
    printf("Move disk %d from rod %c to rod %c\n", n, from_rod, to_rod);
    hanoi(n - 1, aux_rod, from_rod, to_rod);
}