/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* If a macro is not getting expanded as per your expectation, how will you find out how is it being expanded by the preprocessor?
*/
/* Let Us C, Chap- 12 (The C Preprocessor), Qn No.: C(a) */
/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main()
{
    printf("To see how macros are expanded, use the compiler flag '-E'.\n");
    printf("Command: gcc -E filename.c\n");
    printf("This outputs the file after preprocessing stage.\n");

    return 0;
}