/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* If the string "Alice in wonder land" is fed to the following scanf() statement, what will be the contents of arrays str1, str2, str3 and str4?
*/

/* Let Us C, Chap- 15 (Strings), Qn No.: C(a) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main()
{
    char str1[20], str2[20], str3[20], str4[20];

    printf("Enter the string 'Alice in wonder land': ");
    /* scanf stops reading at the first whitespace character for %s */
    scanf("%s%s%s%s", str1, str2, str3, str4);

    printf("\nContents of arrays:\n");
    printf("str1: %s\n", str1);
    printf("str2: %s\n", str2);
    printf("str3: %s\n", str3);
    printf("str4: %s\n", str4);

    return 0;
}