/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write macro definitions for: Mean, Absolute value, Uppercase to Lowercase, Biggest of three.
*/
/* Let Us C, Chap- 12 (The C Preprocessor), Qn No.: C(b) */
/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

#define MEAN(x, y) ((x + y) / 2.0)
#define ABS(x) ((x) < 0 ? -(x) : (x))
#define TO_LOWER(x) ((x) >= 'A' && (x) <= 'Z' ? (x) + 32 : (x))
#define MAX(x, y, z) ((x) > (y) ? ((x) > (z) ? (x) : (z)) : ((y) > (z) ? (y) : (z)))

int main()
{
    int a, b, c, num;
    char ch;

    printf("Enter two numbers for Mean: ");
    scanf("%d %d", &a, &b);
    printf("Mean: %.2f\n\n", MEAN(a, b));

    printf("Enter a number for Absolute value: ");
    scanf("%d", &num);
    printf("Absolute: %d\n\n", ABS(num));

    printf("Enter an uppercase character: ");
    scanf(" %c", &ch);
    printf("Lowercase: %c\n\n", TO_LOWER(ch));

    printf("Enter three numbers: ");
    scanf("%d %d %d", &a, &b, &c);
    printf("Biggest: %d\n", MAX(a, b, c));

    return 0;
}