/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Read a text file, delete the words 'a', 'the', 'an' and replace each with a blank space. Write to new file.
*/
/* Let Us C, Chap- 19 (File Input/Output), Qn No.: B(j) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

void create_article_file();

int main()
{
    FILE *fp, *ft;
    char word[100];

    create_article_file();

    fp = fopen("articles.txt", "r");
    ft = fopen("clean.txt", "w");

    if (!fp || !ft) exit(1);

    // Basic word-by-word processing using fscanf
    // Note: fscanf skips whitespace, so original spacing formatting 
    // might be lost, but it effectively filters words.
    
    while (fscanf(fp, "%s", word) != EOF)
    {
        if (strcasecmp(word, "a") == 0 || 
            strcasecmp(word, "an") == 0 || 
            strcasecmp(word, "the") == 0)
        {
            fputc(' ', ft); // Replace with blank
        }
        else
        {
            fprintf(ft, "%s ", word);
        }
    }

    printf("Processed file. Articles removed in 'clean.txt'.\n");

    fclose(fp);
    fclose(ft);
    return 0;
}

void create_article_file()
{
    FILE *f = fopen("articles.txt", "w");
    fprintf(f, "The quick brown fox jumps over a lazy dog. It was an honour.");
    fclose(f);
}