/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Use 'interest.h' macros to calculate Simple Interest and Amount.
*/
/* Let Us C, Chap- 12 (The C Preprocessor), Qn No.: C(c) */
/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

#include "interest.h"

int main()
{
    float p, r, t, si, amt;

    printf("Enter Principal, Rate and Time: ");
    scanf("%f %f %f", &p, &r, &t);

    si = SIMPLE_INTEREST(p, r, t);
    amt = AMOUNT(p, si);

    printf("Simple Interest: %.2f\n", si);
    printf("Total Amount: %.2f\n", amt);

    return 0;
}