/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program that stores a set of names of individuals and abbreviates the first and middle name to their first letter.
*/

/* Let Us C, Chap- 16 (Handling Multiple Strings), Qn No.: A(d) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

int main()
{
    char names[5][50];
    char abbr[50];
    int i, j, k, len, space_count;

    printf("Enter 5 full names (First Middle Last):\n");
    for (i = 0; i < 5; i++)
    {
        printf("Name %d: ", i + 1);
        gets(names[i]);
    }

    printf("\nAbbreviated Names:\n");
    for (i = 0; i < 5; i++)
    {
        len = strlen(names[i]);
        space_count = 0;
        k = 0;
        
        // Add first initial
        abbr[k++] = names[i][0];
        abbr[k++] = '.';
        abbr[k++] = ' ';

        // Find spaces to get subsequent parts
        for (j = 0; j < len; j++)
        {
            if (names[i][j] == ' ')
            {
                space_count++;
                if (space_count == 1) // Found start of Middle name
                {
                    abbr[k++] = names[i][j+1];
                    abbr[k++] = '.';
                    abbr[k++] = ' ';
                }
                else if (space_count == 2) // Found start of Last name
                {
                    // Copy the rest of the last name
                    int m = j + 1;
                    while (names[i][m] != '\0')
                    {
                        abbr[k++] = names[i][m++];
                    }
                    // Stop searching
                    break;
                }
            }
        }
        abbr[k] = '\0';
        printf("%s\n", abbr);
    }

    return 0;
}