/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Structure 'employee' (Code, Name, Date of Joining). Display names of employees with tenure >= 3 years.
*/
/* Let Us C, Chap- 17 (Structures), Qn No.: B(e) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

struct date
{
    int day;
    int month;
    int year;
};

struct employee
{
    int code;
    char name[30];
    struct date doj;
};

int main()
{
    struct employee emp[5] = {
        {101, "Amit", {12, 1, 2020}},
        {102, "Sumit", {15, 8, 2023}},
        {103, "Rina", {1, 1, 2018}},
        {104, "Tina", {20, 5, 2022}},
        {105, "Mina", {10, 12, 2025}}
    };
    int n = 5, i;
    struct date current;

    printf("Enter current date (dd mm yyyy): ");
    scanf("%d %d %d", &current.day, &current.month, &current.year);

    printf("\nEmployees with tenure >= 3 years:\n");
    for (i = 0; i < n; i++)
    {
        int years = current.year - emp[i].doj.year;
        
        // Adjust for month/day
        if (current.month < emp[i].doj.month || 
           (current.month == emp[i].doj.month && current.day < emp[i].doj.day))
        {
            years--;
        }

        if (years >= 3)
        {
            printf("%s (Tenure: %d years)\n", emp[i].name, years);
        }
    }

    return 0;
}