/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* The X and Y coordinates of 10 different points are entered through the keyboard. Write a program to find the distance of last point from the first point (sum of distances between consecutive points).
*/

/* Let Us C, Chap- 13 (Arrays), Qn No.: B(i) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main()
{
    double x[10], y[10];
    double total_distance = 0.0;
    int i;

    printf("Enter coordinates (x, y) for 10 points:\n");
    for (i = 0; i < 10; i++)
    {
        printf("Point %d: ", i + 1);
        scanf("%lf %lf", &x[i], &y[i]);
    }

    // Sum of distances between consecutive points P(i) and P(i+1)
    for (i = 0; i < 9; i++)
    {
        double dx = x[i+1] - x[i];
        double dy = y[i+1] - y[i];
        total_distance += sqrt(dx*dx + dy*dy);
    }

    printf("\nTotal distance from first to last point: %.2f\n", total_distance);

    return 0;
}