/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to add two 6 x 6 matrices.
*/

/* Let Us C, Chap- 14 (Multidimensional Arrays), Qn No.: C(f) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    int mat1[6][6], mat2[6][6], sum[6][6];
    int i, j;

    // Initializing matrices with some values automatically 
    // to avoid asking user to enter 72 numbers.
    printf("Initializing two 6x6 matrices with sample data...\n");
    
    for (i = 0; i < 6; i++)
    {
        for (j = 0; j < 6; j++)
        {
            mat1[i][j] = i + j;       // Example data
            mat2[i][j] = i * j;       // Example data
        }
    }

    // Adding matrices
    for (i = 0; i < 6; i++)
    {
        for (j = 0; j < 6; j++)
        {
            sum[i][j] = mat1[i][j] + mat2[i][j];
        }
    }

    printf("\nSum of the two 6x6 matrices:\n");
    for (i = 0; i < 6; i++)
    {
        for (j = 0; j < 6; j++)
        {
            printf("%4d ", sum[i][j]);
        }
        printf("\n");
    }

    return 0;
}