/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program using pointers to find the smallest number in an array of 25 integers.
*/

/* Let Us C, Chap- 13 (Arrays), Qn No.: B(c) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main()
{
    int arr[25], i, min;
    int *ptr;

    printf("Enter 25 integers:\n");
    for (i = 0; i < 25; i++)
    {
        scanf("%d", &arr[i]);
    }

    ptr = arr; // Point to start of array
    min = *ptr; // Initialize min with first element

    for (i = 1; i < 25; i++)
    {
        ptr++; // Move pointer to next element
        if (*ptr < min)
        {
            min = *ptr;
        }
    }

    printf("\nSmallest number is: %d\n", min);

    return 0;
}