/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to count the number of occurrences of any two vowels in succession in a line of text.
*/

/* Let Us C, Chap- 16 (Handling Multiple Strings), Qn No.: A(e) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

int is_vowel(char c)
{
    c = tolower(c);
    return (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u');
}

int main()
{
    char str[100];
    int i, count = 0;

    printf("Enter a line of text: ");
    gets(str);

    printf("Occurrences found:\n");
    for (i = 0; str[i] != '\0'; i++)
    {
        if (is_vowel(str[i]) && is_vowel(str[i+1]))
        {
            printf("'%c%c' ", str[i], str[i+1]);
            count++;
        }
    }

    printf("\n\nTotal number of successive vowels: %d\n", count);

    return 0;
}