/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Rewrite the showbits() function using the _BV macro.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(j) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

/* _BV(x) macro usually expands to (1 << x) */
#define _BV(x) (1 << x)

void showbits(unsigned char n);

int main()
{
    unsigned char num;

    printf("Enter an 8-bit number: ");
    scanf("%hhu", &num);

    printf("Binary representation: ");
    showbits(num);
    printf("\n");

    return 0;
}

void showbits(unsigned char n)
{
    int i;
    unsigned char mask;
    
    for (i = 7; i >= 0; i--)
    {
        mask = _BV(i);
        if ((n & mask) == 0)
            printf("0");
        else
            printf("1");
    }
}