/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Receive an 8-bit number. Check if 3rd and 5th bits are ON. If yes, put them OFF.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(h) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned char num;
    unsigned char mask = (1 << 3) | (1 << 5); // Bits 3 and 5

    printf("Enter an 8-bit number: ");
    scanf("%hhu", &num);

    if ((num & mask) == mask)
    {
        printf("Bits 3 and 5 are ON. Turning them OFF...\n");
        // XOR with mask toggles 1 to 0 (since they are 1)
        // OR: AND with complement mask (~mask)
        num = num & ~mask;
    }
    else
    {
        printf("Bits 3 and 5 are NOT both ON. No change.\n");
    }

    printf("Final Value: %d (0x%02X)\n", num, num);

    return 0;
}