/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Receive an 8-bit number and set its odd bits to 1.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(g) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned char num, res;

    printf("Enter an 8-bit number: ");
    scanf("%hhu", &num);

    // Odd bits usually refer to positions 1, 3, 5, 7.
    // Mask: 1010 1010 (binary) = 0xAA
    // OR operation sets bits to 1.
    
    res = num | 0xAA;

    printf("Original: 0x%02X\n", num);
    printf("Result:   0x%02X\n", res);

    return 0;
}