/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to scan an 8-bit number and check whether its 3rd, 6th and 7th bit is on.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(d) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned char num;

    printf("Enter an 8-bit integer (0-255): ");
    scanf("%hhu", &num);

    // Checking bits 3, 6, 7. 
    // Assuming 0-based indexing: 3rd bit is index 3 (value 8), 6th is index 6 (64), 7th is index 7 (128).
    
    unsigned char mask = (1 << 3) | (1 << 6) | (1 << 7);

    if ((num & mask) == mask)
        printf("Bits 3, 6, and 7 are ALL ON.\n");
    else
        printf("Bits 3, 6, and 7 are NOT all on.\n");

    return 0;
}