/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Receive an 8-bit number. Check if 3rd and 5th bits are OFF. If yes, put them ON.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(i) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned char num;
    unsigned char mask = (1 << 3) | (1 << 5);

    printf("Enter an 8-bit number: ");
    scanf("%hhu", &num);

    // Check if bits are OFF. (num & mask) should be 0.
    if ((num & mask) == 0)
    {
        printf("Bits 3 and 5 are OFF. Turning them ON...\n");
        num = num | mask;
    }
    else
    {
        printf("Bits 3 and 5 are NOT both OFF. No change.\n");
    }

    printf("Final Value: %d (0x%02X)\n", num, num);

    return 0;
}