/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Rewrite expressions using bitwise compound assignment operators.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    int a = 10, b = 20, c = 5;

    printf("Original values: a=%d, b=%d, c=%d\n", a, b, c);

    // a = a | 3
    a |= 3;
    printf("a |= 3        -> %d\n", a);

    // a = a & 0x48
    a &= 0x48;
    printf("a &= 0x48     -> %d\n", a);

    // b = b ^ 0x22
    b ^= 0x22;
    printf("b ^= 0x22     -> %d\n", b);

    // c = c << 2
    c <<= 2;
    printf("c <<= 2       -> %d\n", c);

    return 0;
}