/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* What will be the output of the provided program segment involving bitwise operators?
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: A(d) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    int i = 32, j = 65, k, l, m, n, o, p;
    
    k = i | 35; 
    l = ~k; 
    m = i & j;
    n = j ^ 32; 
    o = j << 2; 
    p = i >> 5;

    printf("k = %d l = %d m = %d\n", k, l, m);
    printf("n = %d o = %d p = %d\n", n, o, p);

    return 0;
}