/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Determine if an animal is Carnivore/Herbivore and its type (Canine, Feline, Cetacean, Marsupial) based on bits in an integer.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: A(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

struct animal
{
    char name[30];
    int type;
};

int main()
{
    struct animal a = {"OCELOT", 18};
    int type = a.type;

    printf("Animal: %s\n", a.name);

    // Check Bit 4 for Diet (Assuming 1=Carnivore, 0=Herbivore based on context)
    if (type & (1 << 4))
        printf("Diet: Carnivore\n");
    else
        printf("Diet: Herbivore\n");

    // Check Bits 0-3 for Family
    printf("Family: ");
    if (type & (1 << 0)) printf("Canine ");
    if (type & (1 << 1)) printf("Feline ");
    if (type & (1 << 2)) printf("Cetacean ");
    if (type & (1 << 3)) printf("Marsupial ");
    printf("\n");

    return 0;
}