/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* What is the hexadecimal equivalent of the following binary numbers?
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(a) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    // Binary numbers represented as string literals for reference
    // 01011010
    // 11000011
    // 1010101001110101
    // 111100001011010

    printf("Binary: 01011010          -> Hex: 0x%X\n", 0b01011010);
    printf("Binary: 11000011          -> Hex: 0x%X\n", 0b11000011);
    printf("Binary: 1010101001110101  -> Hex: 0x%X\n", 0b1010101001110101);
    printf("Binary: 111100001011010   -> Hex: 0x%X\n", 0b111100001011010);

    /* Note: Binary literals (0b...) are a standard C extension (GCC) and part of C23 standard. */
    
    return 0;
}