/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a program to generate 4 images of birds flying in the sky with a computer's mouse in their beak using OpenAI Image API.
*/
/* Let Us C, Chap- 24 (Interaction with ChatGPT through C), Qn No.: B(b) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */

/* NOTE: These programs require the 'libcurl' library to compile.
   Command: gcc luc118.c -o output -lcurl */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

/* Pre-requisites:
   1. Install libcurl.
   2. Get OpenAI API Key.
*/

#define API_KEY "YOUR_OPENAI_API_KEY_HERE"

int main(void) {
    CURL *curl;
    CURLcode res;
    
    const char *url = "https://api.openai.com/v1/images/generations";
    
    // JSON Payload: 4 images, 1024x1024
    const char *data = "{"
                       "\"prompt\": \"Birds flying in the sky with a computer mouse in their beak\","
                       "\"n\": 4,"
                       "\"size\": \"1024x1024\""
                       "}";

    struct curl_slist *headers = NULL;
    char auth_header[100];
    sprintf(auth_header, "Authorization: Bearer %s", API_KEY);

    curl = curl_easy_init();
    if(curl) {
        headers = curl_slist_append(headers, "Content-Type: application/json");
        headers = curl_slist_append(headers, auth_header);
        
        curl_easy_setopt(curl, CURLOPT_URL, url);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data);
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        
        // For simplicity, we print the JSON response to stdout.
        // The response will contain URLs to the generated images.
        printf("Sending request to OpenAI Image API...\n\n");
        res = curl_easy_perform(curl);

        if(res != CURLE_OK)
            fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
        
        printf("\n\nCheck the JSON output above for 'url' fields to view images.\n");

        curl_slist_free_all(headers);
        curl_easy_cleanup(curl);
    }
    return 0;
}