/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Receive an unsigned 16-bit integer and exchange the contents of its 2 bytes using bitwise operators.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(e) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned short num, swapped;

    printf("Enter a 16-bit number (0-65535): ");
    scanf("%hu", &num);

    // Exchange bytes:
    // 1. (num & 0xFF00) >> 8 : Move High Byte to Low Byte position
    // 2. (num & 0x00FF) << 8 : Move Low Byte to High Byte position
    
    swapped = ((num & 0xFF00) >> 8) | ((num & 0x00FF) << 8);

    printf("Original: %hu (Hex: 0x%04X)\n", num, num);
    printf("Swapped:  %hu (Hex: 0x%04X)\n", swapped, swapped);

    return 0;
}