/*
 * Author  : Amit Dutta <amitdutta4255@gmail.com>
 * Date    : 08 Feb 2026
 * Repo    : https://github.com/notamitgamer/bsc
 * License : MIT License (See the LICENSE file for details)
 * Copyright (c) 2026 Amit Dutta
 */

/* Write a function checkbits(x, p, n) which returns true if all 'n' bits starting from position 'p' are turned on.
*/
/* Let Us C, Chap- 21 (Operations on Bits), Qn No.: B(c) */

/* This file is auto-generated by a bot. */
/* This code is not compiled; it is for reference only. */


#include <stdio.h>
#include <stdlib.h>

int checkbits(unsigned int x, int p, int n);

int main()
{
    unsigned int x;
    int p, n;

    printf("Enter number (x): ");
    scanf("%u", &x);
    printf("Enter starting position (p) and count (n): ");
    scanf("%d %d", &p, &n);

    if (checkbits(x, p, n))
        printf("TRUE: %d bits starting at %d are ON.\n", n, p);
    else
        printf("FALSE: Not all specified bits are ON.\n");

    return 0;
}

int checkbits(unsigned int x, int p, int n)
{
    unsigned int mask;
    
    // Create a mask of n 1s. E.g., if n=3, mask=000...0111
    mask = (1 << n) - 1;
    
    // Shift mask to position p
    mask = mask << p;

    // Check if bits in x match the mask
    return (x & mask) == mask;
}